PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS T000_CADASTROS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME TEXT NOT NULL,
  NUMERO_CASA TEXT NOT NULL UNIQUE,
  EMAIL TEXT NOT NULL UNIQUE,
  TELEFONE TEXT,
  SENHA TEXT NOT NULL,
  TIPO_USUARIO TEXT NOT NULL DEFAULT 'morador',
  SENHA_TEMPORARIA INTEGER NOT NULL DEFAULT 0,
  SITUACAO TEXT NOT NULL DEFAULT 'Ativo',
  DATA_CADASTRO TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_T000_CADASTROS_NUMERO_CASA
  ON T000_CADASTROS (NUMERO_CASA);

CREATE TABLE IF NOT EXISTS T001_USUARIOS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME TEXT NOT NULL,
  TELEFONE TEXT NOT NULL,
  EMAIL TEXT,
  NUMERO_CASA TEXT NOT NULL UNIQUE,
  TIPO_USUARIO TEXT NOT NULL DEFAULT 'morador',
  SITUACAO TEXT NOT NULL DEFAULT 'Ativo'
);

CREATE TABLE IF NOT EXISTS T002_RESIDENCIAS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USUARIO_ID INTEGER NOT NULL,
  ENDERECO TEXT NOT NULL,
  NUMERO TEXT NOT NULL,
  OBSERVACAO TEXT,
  FOREIGN KEY (USUARIO_ID) REFERENCES T001_USUARIOS (ID)
);

CREATE TABLE IF NOT EXISTS T003_COBRANCAS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  RESIDENCIA_ID INTEGER NOT NULL,
  MES_REFERENCIA TEXT NOT NULL,
  VALOR REAL NOT NULL,
  DATA_VENCIMENTO TEXT NOT NULL,
  SITUACAO TEXT NOT NULL DEFAULT 'Pendente',
  UNIQUE (RESIDENCIA_ID, MES_REFERENCIA),
  FOREIGN KEY (RESIDENCIA_ID) REFERENCES T002_RESIDENCIAS (ID)
);

CREATE TABLE IF NOT EXISTS T004_PAGAMENTOS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  COBRANCA_ID INTEGER NOT NULL,
  VALOR_PAGO REAL NOT NULL,
  DATA_PAGAMENTO TEXT NOT NULL,
  FORMA_PAGAMENTO TEXT NOT NULL,
  OBSERVACAO TEXT,
  FOREIGN KEY (COBRANCA_ID) REFERENCES T003_COBRANCAS (ID)
);

CREATE TABLE IF NOT EXISTS T005_AVISOS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TITULO TEXT NOT NULL,
  MENSAGEM TEXT NOT NULL,
  DATA_PUBLICACAO TEXT NOT NULL,
  TIPO_AVISO TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS T006_OCORRENCIAS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USUARIO_ID INTEGER NOT NULL,
  TIPO_OCORRENCIA TEXT NOT NULL,
  DESCRICAO TEXT NOT NULL,
  DATA_ABERTURA TEXT NOT NULL,
  SITUACAO TEXT NOT NULL DEFAULT 'Aberta',
  FOREIGN KEY (USUARIO_ID) REFERENCES T001_USUARIOS (ID)
);
